//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeLevel
    {
        public int ID { get; set; }
        public string Grade { get; set; }
        public string GradeText { get; set; }
        public string GradeLevel1 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
